# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'page.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1920, 1080)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_clock = QtWidgets.QLabel(self.centralwidget)
        self.label_clock.setGeometry(QtCore.QRect(0, 0, 1080, 1080))
        self.label_clock.setText("")
        self.label_clock.setObjectName("label_clock")
        self.label_T1 = QtWidgets.QLabel(self.centralwidget)
        self.label_T1.setGeometry(QtCore.QRect(1080, 0, 840, 340))
        self.label_T1.setFrameShape(QtWidgets.QFrame.Box)
        self.label_T1.setText("")
        self.label_T1.setObjectName("label_T1")
        self.label_T2 = QtWidgets.QLabel(self.centralwidget)
        self.label_T2.setGeometry(QtCore.QRect(1080, 340, 840, 340))
        self.label_T2.setFrameShape(QtWidgets.QFrame.Box)
        self.label_T2.setText("")
        self.label_T2.setObjectName("label_T2")
        self.label_T3 = QtWidgets.QLabel(self.centralwidget)
        self.label_T3.setGeometry(QtCore.QRect(1080, 680, 840, 340))
        self.label_T3.setFrameShape(QtWidgets.QFrame.Box)
        self.label_T3.setText("")
        self.label_T3.setObjectName("label_T3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1920, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
